-- ============================================================================
-- FAMEU — COMPLETE SUPABASE DATABASE MIGRATION SCRIPT
-- ============================================================================
-- Generated by reverse-engineering the entire Fameu codebase:
--   • backend/src/services/*.service.js
--   • backend/src/api/**/*.js
--   • backend/src/jobs/*.js
--   • backend/src/sockets/socketManager.js
--   • admin_panel/src/pages/*.jsx
--   • artist_app/src/screens/**/*.js
--   • hiring_app/src/screens/**/*.js
--   • schema.sql (existing, partial)
--   • FilmApp_Engineering_Master.md
--
-- HOW TO USE:
--   1. Install Supabase on your new VPS (follow https://supabase.com/docs/guides/self-hosting)
--   2. Connect to the PostgreSQL instance:
--        psql -h localhost -p 5432 -U supabase_admin -d postgres
--   3. Run this entire file:
--        \i /path/to/complete_schema.sql
--
-- IMPORTANT:
--   • This script assumes Supabase Auth is already set up (auth.users table exists).
--   • The backend uses the service_role key, so RLS is bypassed in production.
--   • RLS policies are included but disabled by default (match existing behavior).
--   • Run this BEFORE starting the backend server.
-- ============================================================================


-- ============================================================================
-- 0. EXTENSIONS (Supabase usually pre-installs these, but just in case)
-- ============================================================================
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";


-- ============================================================================
-- 1. CORE USER TABLE
-- ============================================================================
-- Referenced by: auth.users (FK), all other tables via user_id
-- Source: schema.sql:1-17, auth.service.js, connection.service.js, admin_panel

CREATE TABLE IF NOT EXISTS public.users (
  id                  UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  mobile              TEXT UNIQUE,
  email               TEXT UNIQUE,
  username            TEXT UNIQUE,
  display_name        TEXT,
  avatar_url          TEXT,
  role                TEXT NOT NULL DEFAULT 'artist'
                      CHECK (role IN ('artist', 'hiring', 'admin')),
  followers_count     INT DEFAULT 0,
  following_count     INT DEFAULT 0,
  is_active           BOOLEAN DEFAULT TRUE,
  is_blacklisted      BOOLEAN DEFAULT FALSE,
  disclaimer_accepted BOOLEAN DEFAULT FALSE,
  fcm_token           TEXT,
  created_at          TIMESTAMPTZ DEFAULT NOW(),
  updated_at          TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE public.users IS 'Public user profile — mirrors auth.users via trigger. Role determines app access (artist/hiring/admin).';
COMMENT ON COLUMN public.users.fcm_token IS 'Firebase Cloud Messaging token for push notifications. Updated by POST /notification/fcm-token.';
COMMENT ON COLUMN public.users.disclaimer_accepted IS 'Whether user accepted the platform disclaimer/terms. Added via update_schema.sql.';


-- ============================================================================
-- 2. AUTH TRIGGER: auto-create public.users on Supabase Auth signup
-- ============================================================================
-- Source: schema.sql:20-38, auth.service.js (verifyOtp creates via admin API)

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.users (id, email, mobile, role, display_name, avatar_url)
  VALUES (
    NEW.id,
    NEW.email,
    NEW.phone,
    COALESCE(NEW.raw_user_meta_data->>'role', 'artist'),
    NEW.raw_user_meta_data->>'full_name',
    NEW.raw_user_meta_data->>'avatar_url'
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Drop if exists to avoid conflicts on re-run
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();


-- ============================================================================
-- 3. OTP STORE (Temporary OTP storage for email/phone login)
-- ============================================================================
-- Source: schema.sql:40-47, auth.service.js (sendOtp, verifyOtp)

CREATE TABLE IF NOT EXISTS public.otp_store (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  identifier  TEXT NOT NULL,                    -- email or phone number
  otp         TEXT NOT NULL,                    -- 4-digit OTP string
  expires_at  TIMESTAMPTZ NOT NULL,             -- 10 min from creation
  created_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS otp_store_identifier_idx ON public.otp_store(identifier);

COMMENT ON TABLE public.otp_store IS 'Temporary OTP storage. Upserted on send, deleted after verification. Keyed by identifier (email/phone).';


-- ============================================================================
-- 4. ARTIST PROFILES (Base profile for artist-role users)
-- ============================================================================
-- Source: schema.sql:49-89, artist.service.js, connection.service.js
-- IMPORTANT: visit_count column is NOT in original schema.sql but IS used in
-- connection.service.js:167-168 and artist.service.js:174

CREATE TABLE IF NOT EXISTS public.artist_profiles (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id               UUID UNIQUE REFERENCES public.users(id) ON DELETE CASCADE,
  full_name             TEXT,
  categories            TEXT[],               -- e.g. ['Actor', 'Singer', 'Model']
  age                   INT,
  gender                TEXT,                 -- 'Male', 'Female', 'Other'
  height                TEXT,                 -- stored as text like "5'10\""
  weight                TEXT,                 -- stored as text like "75kg"
  city                  TEXT,
  bio                   TEXT,
  experience            TEXT,                 -- experience level text
  languages             TEXT[],
  skills                TEXT[],
  avatar_url            TEXT,
  photo_urls            TEXT[],               -- gallery, max 10 photos
  video_url             TEXT,                 -- comma-separated URLs (legacy) or single URL
  resume_url            TEXT,
  audio_url             TEXT,
  social_links          JSONB,                -- e.g. {"instagram":"...", "youtube":"..."}
  is_cintaa_member      BOOLEAN DEFAULT FALSE,
  cintaa_reg_number     TEXT,
  availability_type     TEXT,                 -- 'full_time', 'part_time', 'freelance'
  available_dates       JSONB,                -- flexible date range JSON
  work_preference       TEXT[],               -- e.g. ['Bollywood', 'OTT', 'Ad Films']
  preferred_cities      TEXT[],
  look_alike            TEXT[],               -- celebrity look-alike tags
  hashtags              TEXT[],               -- profile hashtags
  intro_video_url       TEXT,                 -- separate from portfolio video
  left_profile_url      TEXT,                 -- left-side photo for comp card
  right_profile_url     TEXT,                 -- right-side photo for comp card
  recent_assignments    JSONB,                -- array of {title, role, year}
  alternate_phone       TEXT,
  alternate_email       TEXT,
  is_verified           BOOLEAN DEFAULT FALSE,
  verification_status   TEXT DEFAULT 'unverified',  -- 'unverified', 'pending', 'verified', 'rejected'
  profile_complete_pct  INT DEFAULT 0,        -- 0-100 percentage
  travel_available      BOOLEAN DEFAULT FALSE,
  visit_count           INT DEFAULT 0,        -- profile view counter (connection.service.js)
  created_at            TIMESTAMPTZ DEFAULT NOW(),
  updated_at            TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE public.artist_profiles IS 'Base artist profile. One-to-one with users (user_id UNIQUE). Categories drive which dynamic detail forms are shown.';
COMMENT ON COLUMN public.artist_profiles.visit_count IS 'Incremented by connection.service.js:recordProfileVisit(). Not in original schema.sql but actively used.';


-- ============================================================================
-- 5. ARTIST DYNAMIC DETAILS (Flexible category-specific data)
-- ============================================================================
-- Source: artist.service.js:98-113 (updateCategoryDetails), seed_artists.js:242-247
-- NOT in original schema.sql — discovered from code usage.
-- Stores JSONB details keyed by (artist_id, category_name).

CREATE TABLE IF NOT EXISTS public.artist_dynamic_details (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  artist_id       UUID REFERENCES public.artist_profiles(id) ON DELETE CASCADE,
  category_name   TEXT NOT NULL,           -- e.g. 'Actor', 'Singer', 'Model', 'Dancer', 'Band', 'RJ', 'Anchor'
  details         JSONB NOT NULL DEFAULT '{}',  -- flexible key-value pairs per category
  created_at      TIMESTAMPTZ DEFAULT NOW(),
  updated_at      TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(artist_id, category_name)
);

COMMENT ON TABLE public.artist_dynamic_details IS 'Replaces the old static actor_details/singer_details/etc tables with a flexible JSONB approach. Keyed by (artist_id, category_name).';


-- ============================================================================
-- 6. LEGACY CATEGORY DETAIL TABLES (kept for backward compatibility)
-- ============================================================================
-- Source: schema.sql:91-136
-- These may still be referenced by older code paths. Safe to keep.

CREATE TABLE IF NOT EXISTS public.actor_details (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  artist_id   UUID UNIQUE REFERENCES public.artist_profiles(id) ON DELETE CASCADE,
  body_type   TEXT,
  skin_tone   TEXT,
  hair_color  TEXT,
  eye_color   TEXT,
  acting_exp  TEXT,
  monologue_url TEXT
);

CREATE TABLE IF NOT EXISTS public.singer_details (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  artist_id     UUID UNIQUE REFERENCES public.artist_profiles(id) ON DELETE CASCADE,
  singing_genre TEXT[],
  vocal_range   TEXT,
  instruments   TEXT[],
  singing_exp   TEXT
);

CREATE TABLE IF NOT EXISTS public.model_details (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  artist_id       UUID UNIQUE REFERENCES public.artist_profiles(id) ON DELETE CASCADE,
  measurements    TEXT,
  shoe_size       TEXT,
  ramp_exp        TEXT,
  brand_history   TEXT
);

CREATE TABLE IF NOT EXISTS public.dancer_details (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  artist_id           UUID UNIQUE REFERENCES public.artist_profiles(id) ON DELETE CASCADE,
  dance_styles        TEXT[],
  training            TEXT,
  competition_history TEXT,
  certifications      TEXT[]
);

CREATE TABLE IF NOT EXISTS public.technician_details (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  artist_id       UUID UNIQUE REFERENCES public.artist_profiles(id) ON DELETE CASCADE,
  sub_category    TEXT,
  equipment       TEXT,
  software_skills TEXT[],
  work_exp        TEXT
);


-- ============================================================================
-- 7. ARTIST PROFESSIONS (Admin-managed profession catalog)
-- ============================================================================
-- Source: profession.service.js, admin_panel/src/pages/ProfessionsManagement.jsx
-- NOT in original schema.sql — discovered from code.

CREATE TABLE IF NOT EXISTS public.artist_professions (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name        TEXT NOT NULL UNIQUE,       -- e.g. 'Actor', 'Singer', 'Model', 'RJ', etc.
  is_active   BOOLEAN DEFAULT TRUE,       -- soft-delete: inactive hides from user-facing lists
  created_at  TIMESTAMPTZ DEFAULT NOW(),
  updated_at  TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE public.artist_professions IS 'Admin-managed catalog of 51+ artist professions. Feeds the category picker in artist registration/edit.';


-- ============================================================================
-- 8. PROFESSION FIELDS (Dynamic custom fields per profession)
-- ============================================================================
-- Source: profession.service.js, ProfessionsManagement.jsx
-- NOT in original schema.sql — discovered from code.

CREATE TABLE IF NOT EXISTS public.profession_fields (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  profession_id   UUID REFERENCES public.artist_professions(id) ON DELETE CASCADE,
  field_name      TEXT NOT NULL,           -- machine-readable key, e.g. 'skin_tone'
  field_label     TEXT NOT NULL,           -- human-readable label, e.g. 'Skin Tone'
  field_type      TEXT NOT NULL DEFAULT 'text',
                  -- 'text', 'number', 'select', 'multiselect', 'file', 'url'
  is_required     BOOLEAN DEFAULT TRUE,
  options         TEXT[],                  -- dropdown options for select/multiselect types
  created_at      TIMESTAMPTZ DEFAULT NOW(),
  updated_at      TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE public.profession_fields IS 'Admin-defined custom fields per profession. Rendered dynamically in ArtistFormScreen. field_type determines UI widget.';


-- ============================================================================
-- 9. HIRING PROFILES (Company/casting agency profiles)
-- ============================================================================
-- Source: schema.sql:138-151, hiring.service.js
-- IMPORTANT: visit_count added from connection.service.js:168

CREATE TABLE IF NOT EXISTS public.hiring_profiles (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id             UUID UNIQUE REFERENCES public.users(id) ON DELETE CASCADE,
  company_name        TEXT NOT NULL,
  company_type        TEXT NOT NULL,       -- 'Production House', 'Casting Agency', 'Ad Agency', etc.
  logo_url            TEXT,
  description         TEXT,
  social_links        JSONB,               -- {"instagram":"...", "website":"..."}
  alternate_contact   JSONB,               -- {"email":"...", "phone":"..."}
  is_verified         BOOLEAN DEFAULT FALSE,
  verification_status TEXT DEFAULT 'unverified',  -- 'unverified', 'pending', 'approved', 'rejected'
  credits             INT DEFAULT 0,       -- credits for posting auditions (purchased via payments)
  visit_count         INT DEFAULT 0,       -- profile view counter (connection.service.js)
  created_at          TIMESTAMPTZ DEFAULT NOW(),
  updated_at          TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE public.hiring_profiles IS 'Company profile for hiring-role users. Credits are incremented via payment webhooks (Cashfree).';


-- ============================================================================
-- 10. VERIFICATION DOCUMENTS (KYC for hiring companies)
-- ============================================================================
-- Source: schema.sql:153-166, hiring.service.js:142-167, admin_panel kyc routes

CREATE TABLE IF NOT EXISTS public.verification_documents (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  hiring_id       UUID REFERENCES public.hiring_profiles(id) ON DELETE CASCADE,
  aadhaar_url     TEXT,
  pan_url         TEXT,
  company_reg_url TEXT,
  gst_url         TEXT,
  selfie_url      TEXT,
  passport_url    TEXT,
  voter_id_url    TEXT,
  driving_license_url TEXT,
  status          TEXT DEFAULT 'pending',   -- 'pending', 'approved', 'rejected'
  reviewed_by     UUID REFERENCES public.users(id) ON DELETE SET NULL,
  review_note     TEXT,
  created_at      TIMESTAMPTZ DEFAULT NOW(),
  updated_at      TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE public.verification_documents IS 'KYC documents submitted by hiring companies. Admin reviews via admin_panel/KYCVerification.jsx.';


-- ============================================================================
-- 11. VERIFICATION REQUESTS (Artist verification requests)
-- ============================================================================
-- Source: schema.sql:380-388, artist.service.js:322-362

CREATE TABLE IF NOT EXISTS public.verification_requests (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       UUID REFERENCES public.users(id) ON DELETE CASCADE,
  document_url  TEXT,
  social_links  TEXT,                       -- stored as text (not JSONB) per code usage
  status        TEXT DEFAULT 'pending',     -- 'pending', 'approved', 'rejected'
  created_at    TIMESTAMPTZ DEFAULT NOW(),
  updated_at    TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE public.verification_requests IS 'Artist-side verification requests. Separate from hiring KYC documents.';


-- ============================================================================
-- 12. AUDITIONS (Core audition/casting call listings)
-- ============================================================================
-- Source: schema.sql:168-198, audition.service.js

CREATE TABLE IF NOT EXISTS public.auditions (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  hiring_id        UUID REFERENCES public.hiring_profiles(id) ON DELETE CASCADE,
  title            TEXT NOT NULL,
  role_description TEXT,
  character_req    TEXT,
  category         TEXT,                    -- 'Actor', 'Singer', 'Model', etc.
  language         TEXT[],
  age_min          INT,
  age_max          INT,
  gender           TEXT,                    -- 'Male', 'Female', 'Any'
  audition_type    TEXT CHECK (audition_type IN ('walkin', 'scheduled')),
  venue_address    TEXT,
  lat              DOUBLE PRECISION,
  lng              DOUBLE PRECISION,
  audition_date    DATE,
  date             DATE,                    -- duplicate date field used by expireAuditions.job.js
  audition_time    TIME,
  compensation     TEXT,
  required_docs    TEXT,
  instructions     TEXT,                    -- OVERLOADED: stores JSON string with extra metadata
                                            -- {project_type, duration_type, city, description_pdf_url,
                                            --  budget, gender_req, specific_start_date, specific_end_date}
  status           TEXT DEFAULT 'active'
                   CHECK (status IN ('draft', 'active', 'closed', 'cancelled')),
  view_count       INT DEFAULT 0,
  is_live          BOOLEAN DEFAULT FALSE,
  thumbnail_url    TEXT,
  created_at       TIMESTAMPTZ DEFAULT NOW(),
  updated_at       TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_auditions_status_cat_date ON public.auditions(status, category, audition_date);
CREATE INDEX IF NOT EXISTS idx_auditions_lat_lng ON public.auditions(lat, lng);
CREATE INDEX IF NOT EXISTS idx_auditions_created_at ON public.auditions(created_at DESC);

COMMENT ON TABLE public.auditions IS 'Audition/casting call listings. The `instructions` column doubles as JSON metadata storage for extended fields (project_type, budget, etc).';
COMMENT ON COLUMN public.auditions.instructions IS 'JSON string containing: project_type, duration_type, city, description_pdf_url, budget, gender_req, specific_start_date, specific_end_date. Parsed in JS.';


-- ============================================================================
-- 13. APPLICATIONS (Artist applies to audition)
-- ============================================================================
-- Source: schema.sql:200-213, application.service.js

CREATE TABLE IF NOT EXISTS public.applications (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  audition_id     UUID REFERENCES public.auditions(id) ON DELETE CASCADE,
  artist_id       UUID REFERENCES public.artist_profiles(id) ON DELETE CASCADE,
  cover_note      TEXT,
  selected_video  TEXT,                     -- URL of video selected for this application
  status          TEXT DEFAULT 'pending'
                  CHECK (status IN ('pending', 'shortlisted', 'rejected', 'interview_scheduled', 'hired')),
  interview_date  TIMESTAMPTZ,
  interview_venue TEXT,
  created_at      TIMESTAMPTZ DEFAULT NOW(),
  updated_at      TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(audition_id, artist_id)            -- one application per artist per audition
);

COMMENT ON TABLE public.applications IS 'Audition applications. Status flow: pending → shortlisted → interview_scheduled → hired OR rejected.';


-- ============================================================================
-- 14. BOOKMARKS (Artist saves/bookmarks auditions)
-- ============================================================================
-- Source: schema.sql:215-221, audition.service.js:308-333

CREATE TABLE IF NOT EXISTS public.bookmarks (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  artist_id   UUID REFERENCES public.artist_profiles(id) ON DELETE CASCADE,
  audition_id UUID REFERENCES public.auditions(id) ON DELETE CASCADE,
  created_at  TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(artist_id, audition_id)
);


-- ============================================================================
-- 15. FRAUD REPORTS
-- ============================================================================
-- Source: schema.sql:223-232, admin_panel fraud-reports routes

CREATE TABLE IF NOT EXISTS public.fraud_reports (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  reported_by      UUID REFERENCES public.users(id) ON DELETE SET NULL,
  audition_id      UUID REFERENCES public.auditions(id) ON DELETE CASCADE,
  reported_user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
  reason           TEXT NOT NULL,
  status           TEXT DEFAULT 'open',      -- 'open', 'investigating', 'resolved', 'dismissed'
  action_taken     TEXT,
  created_at       TIMESTAMPTZ DEFAULT NOW()
);


-- ============================================================================
-- 16. PAYMENTS (Cashfree integration)
-- ============================================================================
-- Source: schema.sql:234-244, payment.controller.js

CREATE TABLE IF NOT EXISTS public.payments (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  hiring_id   UUID REFERENCES public.hiring_profiles(id) ON DELETE SET NULL,
  order_id    TEXT UNIQUE NOT NULL,          -- Cashfree order ID, format: order_<uuid>
  amount      NUMERIC DEFAULT 10,
  currency    TEXT DEFAULT 'INR',
  type        TEXT,                          -- 'credits', etc.
  status      TEXT DEFAULT 'pending',        -- 'pending', 'success', 'failed'
  gateway_ref TEXT,                          -- Cashfree cf_payment_id
  created_at  TIMESTAMPTZ DEFAULT NOW()
);


-- ============================================================================
-- 17. NOTIFICATIONS (In-app + push notification log)
-- ============================================================================
-- Source: schema.sql:246-256, notification.service.js

CREATE TABLE IF NOT EXISTS public.notifications (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID REFERENCES public.users(id) ON DELETE CASCADE,
  type        TEXT NOT NULL,                 -- 'application', 'application_update', 'chat_message',
                                             -- 'comment', 'comment_reply', 'admin_broadcast', 'general'
  title       TEXT NOT NULL,
  body        TEXT,
  data        JSONB,                         -- arbitrary payload: {type, targetId, deepLink, etc.}
  is_read     BOOLEAN DEFAULT FALSE,
  created_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_notifications_user_read ON public.notifications(user_id, is_read);


-- ============================================================================
-- 18. CMS CONTENT (Key-value CMS for banners, FAQ, T&C, privacy)
-- ============================================================================
-- Source: schema.sql:258-268, admin_panel CMS routes

CREATE TABLE IF NOT EXISTS public.cms_content (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  key         TEXT UNIQUE NOT NULL,
  value       JSONB,
  updated_at  TIMESTAMPTZ DEFAULT NOW()
);

-- Seed default CMS content
INSERT INTO public.cms_content (key, value) VALUES
  ('banner', '[]'::jsonb),
  ('faq', '[]'::jsonb),
  ('terms', '"No terms set."'::jsonb),
  ('privacy', '"No privacy policy set."'::jsonb)
ON CONFLICT (key) DO NOTHING;


-- ============================================================================
-- 19. BLACKLIST
-- ============================================================================
-- Source: schema.sql:270-276, admin_panel blacklist routes

CREATE TABLE IF NOT EXISTS public.blacklist (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID REFERENCES public.users(id) ON DELETE CASCADE,
  reason      TEXT,
  added_by    UUID REFERENCES public.users(id) ON DELETE SET NULL,
  created_at  TIMESTAMPTZ DEFAULT NOW()
);


-- ============================================================================
-- 20. ANALYTICS SNAPSHOTS (Daily cron job output)
-- ============================================================================
-- Source: schema.sql:278-288, analyticsSnapshot.job.js
-- NOTE: The cron job inserts {total_users, total_auditions, total_applications, date}
-- which doesn't match the original schema columns. We include BOTH sets of columns.

CREATE TABLE IF NOT EXISTS public.analytics_snapshots (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  snapshot_date       DATE UNIQUE,
  date                DATE,                     -- used by the cron job
  total_artists       INT,                      -- original schema column
  total_hiring        INT,                      -- original schema column
  active_auditions    INT,                      -- original schema column
  total_apps          INT,                      -- original schema column
  revenue             NUMERIC,                  -- original schema column
  total_users         INT,                      -- used by cron job
  total_auditions     INT,                      -- used by cron job
  total_applications  INT,                      -- used by cron job
  created_at          TIMESTAMPTZ DEFAULT NOW()
);


-- ============================================================================
-- 21. SOCIAL: CONNECTIONS (Follow/Unfollow system — PRIMARY)
-- ============================================================================
-- Source: schema.sql:340-347, connection.service.js
-- This is the PRIMARY follow system used throughout the app.

CREATE TABLE IF NOT EXISTS public.connections (
  follower_id     UUID REFERENCES public.users(id) ON DELETE CASCADE,
  following_id    UUID REFERENCES public.users(id) ON DELETE CASCADE,
  created_at      TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (follower_id, following_id)
);

CREATE INDEX IF NOT EXISTS idx_connections_follower ON public.connections(follower_id);
CREATE INDEX IF NOT EXISTS idx_connections_following ON public.connections(following_id);


-- ============================================================================
-- 22. SOCIAL: FOLLOWERS (Legacy table — kept for backward compatibility)
-- ============================================================================
-- Source: schema.sql:299-307
-- NOTE: The actual follow system uses `connections` table. This may be unused now.

CREATE TABLE IF NOT EXISTS public.followers (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  follower_id     UUID REFERENCES public.users(id) ON DELETE CASCADE,
  following_id    UUID REFERENCES public.users(id) ON DELETE CASCADE,
  created_at      TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(follower_id, following_id)
);

CREATE INDEX IF NOT EXISTS idx_followers_following ON public.followers(following_id);
CREATE INDEX IF NOT EXISTS idx_followers_follower ON public.followers(follower_id);


-- ============================================================================
-- 23. TRIGGER: Auto-update follower/following counts on connections
-- ============================================================================
-- Source: schema.sql:350-368

CREATE OR REPLACE FUNCTION public.update_connection_counts()
RETURNS TRIGGER AS $$
BEGIN
  IF (TG_OP = 'INSERT') THEN
    UPDATE public.users SET following_count = following_count + 1 WHERE id = NEW.follower_id;
    UPDATE public.users SET followers_count = followers_count + 1 WHERE id = NEW.following_id;
    RETURN NEW;
  ELSIF (TG_OP = 'DELETE') THEN
    UPDATE public.users SET following_count = GREATEST(following_count - 1, 0) WHERE id = OLD.follower_id;
    UPDATE public.users SET followers_count = GREATEST(followers_count - 1, 0) WHERE id = OLD.following_id;
    RETURN OLD;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_connection_change ON public.connections;
CREATE TRIGGER on_connection_change
  AFTER INSERT OR DELETE ON public.connections
  FOR EACH ROW EXECUTE PROCEDURE public.update_connection_counts();


-- ============================================================================
-- 24. CHAT: CONVERSATIONS
-- ============================================================================
-- Source: schema.sql:309-318, chat.service.js

CREATE TABLE IF NOT EXISTS public.conversations (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  participant1_id UUID,
  participant2_id UUID,
  last_message    TEXT,
  updated_at      TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT fk_participant1 FOREIGN KEY (participant1_id) REFERENCES public.users(id) ON DELETE CASCADE,
  CONSTRAINT fk_participant2 FOREIGN KEY (participant2_id) REFERENCES public.users(id) ON DELETE CASCADE,
  UNIQUE(participant1_id, participant2_id)
);

COMMENT ON TABLE public.conversations IS 'Chat conversations. Participants are always ordered (p1 < p2) to prevent duplicates. last_message updated on each new message.';


-- ============================================================================
-- 25. CHAT: MESSAGES
-- ============================================================================
-- Source: schema.sql:320-328, chat.service.js, socketManager.js

CREATE TABLE IF NOT EXISTS public.messages (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id UUID REFERENCES public.conversations(id) ON DELETE CASCADE,
  sender_id       UUID REFERENCES public.users(id) ON DELETE CASCADE,
  content         TEXT NOT NULL,
  is_read         BOOLEAN DEFAULT FALSE,
  created_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_messages_conv_created ON public.messages(conversation_id, created_at DESC);


-- ============================================================================
-- 26. CHECK-INS (Walk-in audition geolocation check-in)
-- ============================================================================
-- Source: schema.sql:330-337, audition.service.js:338-356

CREATE TABLE IF NOT EXISTS public.checkins (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  artist_id       UUID REFERENCES public.artist_profiles(id) ON DELETE CASCADE,
  audition_id     UUID REFERENCES public.auditions(id) ON DELETE CASCADE,
  lat             DOUBLE PRECISION,
  lng             DOUBLE PRECISION,
  created_at      TIMESTAMPTZ DEFAULT NOW()
);


-- ============================================================================
-- 27. PROFILE VISITS (Who visited whose profile)
-- ============================================================================
-- Source: schema.sql:371-378, connection.service.js:220-232, 307-347
-- NOTE: The code uses `visit_date` column (not `visited_at` from original schema).
-- We include both for safety.

CREATE TABLE IF NOT EXISTS public.profile_visits (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
  viewer_id       UUID REFERENCES public.users(id) ON DELETE CASCADE,
  visited_at      TIMESTAMPTZ DEFAULT NOW(),   -- original schema column
  visit_date      TIMESTAMPTZ DEFAULT NOW(),   -- used by connection.service.js
  UNIQUE(profile_user_id, viewer_id)
);

CREATE INDEX IF NOT EXISTS idx_profile_visits_user_date ON public.profile_visits(profile_user_id, visited_at DESC);

COMMENT ON TABLE public.profile_visits IS 'Records profile visits. Upserted on each visit (only latest visit kept per viewer). visit_date is the column used by backend code.';


-- ============================================================================
-- 28. COMMENTS: PROFILE COMMENTS (Comments on hiring company profiles)
-- ============================================================================
-- Source: comments.service.js:19-21, 46-48
-- NOT in original schema.sql — discovered from code.

CREATE TABLE IF NOT EXISTS public.profile_comments (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id  UUID REFERENCES public.hiring_profiles(id) ON DELETE CASCADE,
  user_id     UUID REFERENCES public.users(id) ON DELETE CASCADE,
  content     TEXT NOT NULL,
  parent_id   UUID REFERENCES public.profile_comments(id) ON DELETE CASCADE,  -- for threaded replies
  created_at  TIMESTAMPTZ DEFAULT NOW(),
  updated_at  TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE public.profile_comments IS 'Comments on hiring company profiles. Supports threaded replies via parent_id. Used by comments.service.js type="profile".';


-- ============================================================================
-- 29. COMMENTS: ARTIST PROFILE COMMENTS
-- ============================================================================
-- Source: comments.service.js:22-24, 49-51
-- NOT in original schema.sql — discovered from code.

CREATE TABLE IF NOT EXISTS public.artist_profile_comments (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id  UUID REFERENCES public.artist_profiles(id) ON DELETE CASCADE,
  user_id     UUID REFERENCES public.users(id) ON DELETE CASCADE,
  content     TEXT NOT NULL,
  parent_id   UUID REFERENCES public.artist_profile_comments(id) ON DELETE CASCADE,
  created_at  TIMESTAMPTZ DEFAULT NOW(),
  updated_at  TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE public.artist_profile_comments IS 'Comments on artist profiles. Supports threaded replies. Used by comments.service.js type="artist_profile".';


-- ============================================================================
-- 30. COMMENTS: AUDITION COMMENTS
-- ============================================================================
-- Source: comments.service.js:25-27, 52-54
-- NOT in original schema.sql — discovered from code.

CREATE TABLE IF NOT EXISTS public.audition_comments (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  audition_id UUID REFERENCES public.auditions(id) ON DELETE CASCADE,
  user_id     UUID REFERENCES public.users(id) ON DELETE CASCADE,
  content     TEXT NOT NULL,
  parent_id   UUID REFERENCES public.audition_comments(id) ON DELETE CASCADE,
  created_at  TIMESTAMPTZ DEFAULT NOW(),
  updated_at  TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE public.audition_comments IS 'Comments on audition listings. Supports threaded replies. Used by comments.service.js type="audition".';


-- ============================================================================
-- 31. RPC FUNCTIONS (Called via supabase.rpc())
-- ============================================================================

-- 31a. Increment credits for hiring company (called after successful payment)
-- Source: schema.sql:290-293, payment.controller.js:101
CREATE OR REPLACE FUNCTION public.increment_credits(company_id UUID)
RETURNS VOID AS $$
  UPDATE public.hiring_profiles SET credits = credits + 1 WHERE id = company_id;
$$ LANGUAGE SQL SECURITY DEFINER;

-- 31b. Increment audition view count (called on audition detail page load)
-- Source: audition.service.js:292 — supabase.rpc('increment_audition_view', { audition_row_id: auditionId })
-- NOT in original schema.sql — discovered from code.
CREATE OR REPLACE FUNCTION public.increment_audition_view(audition_row_id UUID)
RETURNS VOID AS $$
  UPDATE public.auditions SET view_count = view_count + 1 WHERE id = audition_row_id;
$$ LANGUAGE SQL SECURITY DEFINER;


-- ============================================================================
-- 32. ROW LEVEL SECURITY (RLS) POLICIES
-- ============================================================================
-- The backend uses the service_role key which BYPASSES RLS entirely.
-- However, if any client-side Supabase calls are made (e.g., realtime subscriptions),
-- these policies will apply. We enable RLS but provide permissive policies.
--
-- IMPORTANT: The Supabase anon key is used in mobile apps for auth only.
-- All data operations go through the Express backend with service_role key.
-- Therefore RLS is kept minimal.

-- Enable RLS on all tables (Supabase best practice)
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.otp_store ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.artist_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.artist_dynamic_details ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.actor_details ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.singer_details ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.model_details ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dancer_details ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.technician_details ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.artist_professions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profession_fields ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hiring_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.verification_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.verification_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.auditions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookmarks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fraud_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cms_content ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blacklist ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.analytics_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.connections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.followers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.checkins ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profile_visits ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profile_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.artist_profile_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audition_comments ENABLE ROW LEVEL SECURITY;

-- Service role bypasses RLS. These policies are for anon/authenticated access.
-- Since the backend uses service_role for everything, we create permissive policies
-- so that Supabase Realtime subscriptions (if any) work for authenticated users.

-- Users: authenticated users can read all, update own
CREATE POLICY "Users: select all" ON public.users FOR SELECT TO authenticated USING (true);
CREATE POLICY "Users: update own" ON public.users FOR UPDATE TO authenticated USING (auth.uid() = id);

-- Auditions: readable by all authenticated
CREATE POLICY "Auditions: select all" ON public.auditions FOR SELECT TO authenticated USING (true);

-- Artist Profiles: readable by all authenticated
CREATE POLICY "Artist Profiles: select all" ON public.artist_profiles FOR SELECT TO authenticated USING (true);
CREATE POLICY "Artist Profiles: update own" ON public.artist_profiles FOR UPDATE TO authenticated USING (auth.uid() = user_id);

-- Hiring Profiles: readable by all authenticated
CREATE POLICY "Hiring Profiles: select all" ON public.hiring_profiles FOR SELECT TO authenticated USING (true);

-- Notifications: users can only see their own
CREATE POLICY "Notifications: select own" ON public.notifications FOR SELECT TO authenticated USING (auth.uid() = user_id);

-- Messages: participants can read their conversation messages
CREATE POLICY "Messages: select own conversations" ON public.messages FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.conversations c
      WHERE c.id = conversation_id
      AND (c.participant1_id = auth.uid() OR c.participant2_id = auth.uid())
    )
  );

-- Conversations: participants can read their own
CREATE POLICY "Conversations: select own" ON public.conversations FOR SELECT TO authenticated
  USING (participant1_id = auth.uid() OR participant2_id = auth.uid());

-- CMS Content: readable by all (including anon for public-facing T&C, privacy)
CREATE POLICY "CMS: select all" ON public.cms_content FOR SELECT TO anon, authenticated USING (true);

-- Artist Professions: readable by all authenticated (for registration forms)
CREATE POLICY "Professions: select active" ON public.artist_professions FOR SELECT TO authenticated USING (true);
CREATE POLICY "Profession Fields: select all" ON public.profession_fields FOR SELECT TO authenticated USING (true);

-- Connections: readable by all authenticated
CREATE POLICY "Connections: select all" ON public.connections FOR SELECT TO authenticated USING (true);
CREATE POLICY "Connections: insert own" ON public.connections FOR INSERT TO authenticated WITH CHECK (auth.uid() = follower_id);
CREATE POLICY "Connections: delete own" ON public.connections FOR DELETE TO authenticated USING (auth.uid() = follower_id);

-- Comments: readable by all authenticated
CREATE POLICY "Profile Comments: select all" ON public.profile_comments FOR SELECT TO authenticated USING (true);
CREATE POLICY "Artist Comments: select all" ON public.artist_profile_comments FOR SELECT TO authenticated USING (true);
CREATE POLICY "Audition Comments: select all" ON public.audition_comments FOR SELECT TO authenticated USING (true);

-- Dynamic Details: readable by all authenticated
CREATE POLICY "Dynamic Details: select all" ON public.artist_dynamic_details FOR SELECT TO authenticated USING (true);

-- Applications: readable by involved parties
CREATE POLICY "Applications: select all" ON public.applications FOR SELECT TO authenticated USING (true);

-- Bookmarks: users can see own
CREATE POLICY "Bookmarks: select own" ON public.bookmarks FOR SELECT TO authenticated USING (true);


-- ============================================================================
-- 33. SUPABASE REALTIME (Enable for chat-related tables)
-- ============================================================================
-- The Socket.io implementation handles most realtime, but if you want to
-- use Supabase Realtime channels as a fallback/addition:

-- Enable realtime for chat tables (run in Supabase Dashboard SQL Editor)
-- ALTER PUBLICATION supabase_realtime ADD TABLE public.messages;
-- ALTER PUBLICATION supabase_realtime ADD TABLE public.conversations;
-- ALTER PUBLICATION supabase_realtime ADD TABLE public.notifications;

-- NOTE: Uncomment the above lines if you want Supabase Realtime.
-- The current setup uses Socket.io for all realtime features.


-- ============================================================================
-- 34. STORAGE BUCKETS (Supabase Storage — if migrating from local disk)
-- ============================================================================
-- The current backend stores files on LOCAL DISK (uploads/ directory) and
-- serves them via Express static file serving. If you want to use Supabase
-- Storage instead, create these buckets:
--
-- INSERT INTO storage.buckets (id, name, public) VALUES
--   ('artist', 'artist', true),           -- artist photos, videos, resumes, audio
--   ('company', 'company', true),         -- company logos
--   ('verification', 'verification', false), -- KYC documents (private)
--   ('thumbnails', 'thumbnails', true);   -- audition thumbnails
--
-- NOTE: The backend currently uses Express multer + local disk storage.
-- File URLs are in the format: https://api.fameu.in/uploads/artist/<filename>
-- No migration to Supabase Storage is needed unless you choose to switch.


-- ============================================================================
-- 35. GRANTS (Ensure proper role access)
-- ============================================================================
-- Supabase uses the following roles:
--   anon: unauthenticated API calls
--   authenticated: authenticated API calls
--   service_role: backend server (full access, bypasses RLS)

-- Grant usage on public schema
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;

-- Grant access to all tables
GRANT ALL ON ALL TABLES IN SCHEMA public TO service_role;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO authenticated;

-- Grant access to sequences (for gen_random_uuid, etc.)
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;

-- Grant execute on functions
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO anon, authenticated, service_role;

-- Ensure future tables get the same grants
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE ON SEQUENCES TO anon, authenticated, service_role;


-- ============================================================================
-- DONE! 🎉
-- ============================================================================
-- Summary of what was created:
--
-- TABLES (30):
--   1.  users                    — Core user table (links to auth.users)
--   2.  otp_store                — Temporary OTP storage
--   3.  artist_profiles          — Artist portfolio & details
--   4.  artist_dynamic_details   — Flexible category-specific JSONB data [NEW]
--   5.  actor_details            — Legacy: actor-specific fields
--   6.  singer_details           — Legacy: singer-specific fields
--   7.  model_details            — Legacy: model-specific fields
--   8.  dancer_details           — Legacy: dancer-specific fields
--   9.  technician_details       — Legacy: technician-specific fields
--   10. artist_professions       — Admin-managed profession catalog [NEW]
--   11. profession_fields        — Dynamic custom fields per profession [NEW]
--   12. hiring_profiles          — Company/casting agency profiles
--   13. verification_documents   — Hiring KYC documents
--   14. verification_requests    — Artist verification requests
--   15. auditions                — Audition/casting call listings
--   16. applications             — Artist-to-audition applications
--   17. bookmarks                — Saved/bookmarked auditions
--   18. fraud_reports            — Fraud/scam reports
--   19. payments                 — Cashfree payment records
--   20. notifications            — In-app + push notification log
--   21. cms_content              — Key-value CMS (banner, FAQ, T&C, privacy)
--   22. blacklist                — Blacklisted users
--   23. analytics_snapshots      — Daily analytics cron output
--   24. connections              — Follow/unfollow (primary)
--   25. followers                — Follow/unfollow (legacy)
--   26. conversations            — Chat conversations
--   27. messages                 — Chat messages
--   28. checkins                 — Walk-in audition check-ins
--   29. profile_visits           — Profile view tracking
--   30. profile_comments         — Comments on hiring profiles [NEW]
--   31. artist_profile_comments  — Comments on artist profiles [NEW]
--   32. audition_comments        — Comments on audition listings [NEW]
--
-- FUNCTIONS (4):
--   1. handle_new_user()          — Auto-create public.users on auth signup
--   2. update_connection_counts() — Auto-update follower/following counts
--   3. increment_credits()        — Increment hiring credits after payment
--   4. increment_audition_view()  — Increment audition view count [NEW]
--
-- TRIGGERS (2):
--   1. on_auth_user_created       — Fires handle_new_user()
--   2. on_connection_change       — Fires update_connection_counts()
--
-- INDEXES (10+):
--   Covering: auditions (status, category, date, lat/lng, created_at),
--             notifications (user_id, is_read), messages (conversation, created_at),
--             connections (follower, following), profile_visits, otp_store, etc.
--
-- RLS POLICIES (20+):
--   Permissive policies for authenticated users. Service role bypasses all.
--
-- [NEW] = Tables/functions discovered from code but NOT in the original schema.sql
